apiVersion: apps/v1
kind: Deployment
metadata:
  name: corider-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: corider-backend
  template:
    metadata:
      labels:
        app: corider-backend
    spec:
      containers:
        - name: corider-backend
          image: codewithshahid/corider-backend:latest
          ports:
            - containerPort: 5050
          env:
            - name: PORT
              value: "5050"

